action_id: trunk-whoami
date: 2026-05-22 00:15:33
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1779408933
full_timestamp:
  nanos: 287857000
  seconds: 1779408933
trunk_version: 1.25.0
